# Generated by Django 3.1.1 on 2020-09-16 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='time_answered',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 6, 35, 22, 352503, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
