# Generated by Django 3.1.1 on 2020-09-16 08:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeeQuiz', '0002_choice_time_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='coffeeQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expLevel', models.CharField(max_length=200)),
                ('brewMethod', models.CharField(max_length=200)),
                ('prefTaste', models.CharField(max_length=200)),
                ('time_answered', models.DateTimeField(default=datetime.datetime(2020, 9, 16, 8, 58, 7, 356229, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
