# Generated by Django 3.1.1 on 2020-09-16 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeQuiz', '0003_answers_coffeequiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeequiz',
            name='time_answered',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 9, 6, 5, 832675, tzinfo=utc)),
        ),
    ]
