# Generated by Django 3.1.1 on 2020-09-17 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeQuiz', '0004_auto_20200916_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='coffeequiz',
            name='time_answered',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 17, 13, 31, 249162, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
