# Generated by Django 3.1.1 on 2020-09-18 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeQuiz', '0007_auto_20200918_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeequiz',
            name='time_answered',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 5, 22, 5, 254744, tzinfo=utc)),
        ),
    ]
