# Generated by Django 3.1.1 on 2020-09-18 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeQuiz', '0008_auto_20200918_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeequiz',
            name='time_answered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
