# Generated by Django 3.1 on 2020-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beans',
            name='company',
            field=models.CharField(default='Coffee Cloud', max_length=100),
        ),
        migrations.AddField(
            model_name='beans',
            name='process',
            field=models.CharField(default='Coffee Cloud', max_length=200),
            preserve_default=False,
        ),
    ]
