# Generated by Django 3.1 on 2020-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0007_auto_20200826_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='bean',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beans',
            name='dateRoast',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
