# Generated by Django 3.1 on 2020-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0008_auto_20200830_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='item',
        ),
    ]
