# Generated by Django 3.1 on 2020-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0009_remove_dailylog_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
