# Generated by Django 3.1 on 2020-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0010_auto_20200905_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='bean',
            field=models.CharField(default='User did not input beam', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='cNotes',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='title',
            field=models.CharField(default='User did not input title', max_length=100),
        ),
    ]
