# Generated by Django 3.1 on 2020-09-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0011_auto_20200905_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='dateLogged',
        ),
    ]
