# Generated by Django 3.1 on 2020-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0012_remove_dailylog_datelogged'),
        ('coffeeCloud', '0012_feedback'),
    ]

    operations = [
    ]
