# Generated by Django 3.1.1 on 2020-09-18 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0013_merge_20200916_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='dateLogged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
