# Generated by Django 3.1.1 on 2020-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0015_beans_intendedbrewmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='dateRoast',
            field=models.DateTimeField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beans',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beans',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
