# Generated by Django 3.1.1 on 2020-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeCloud', '0016_auto_20200918_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
